# Generated by Django 2.2 on 2020-09-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_temperature', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather_image', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Weather',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='input_text',
            new_name='lookup_city',
        ),
    ]
