# Generated by Django 2.2 on 2020-09-26 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_auto_20200922_1800'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='weather_image',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='weather_type',
        ),
        migrations.AddField(
            model_name='weather',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='weather',
            name='city_weather',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='weather',
            name='city_weather_image',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='weather',
            name='city_temperature',
            field=models.CharField(default='', max_length=4),
        ),
    ]
