# Generated by Django 2.2 on 2020-09-26 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0005_auto_20200925_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityLookup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='weather',
            name='city_temperature',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='city_weather',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='city_weather_image',
        ),
        migrations.AddField(
            model_name='weather',
            name='temperature',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='weather',
            name='weather',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='weather',
            name='weather_icon',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='weather',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.CityLookup'),
        ),
    ]
