# Generated by Django 2.2 on 2020-09-26 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0006_auto_20200926_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weather',
            name='temperature',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='weather',
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.CharField(default='', max_length=200)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.CityLookup')),
            ],
        ),
    ]
