# Generated by Django 2.2 on 2020-09-26 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0007_auto_20200926_1646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weather',
            old_name='weather_icon',
            new_name='weather',
        ),
        migrations.CreateModel(
            name='WeatherIcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather_icon', models.CharField(default='', max_length=200)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.CityLookup')),
            ],
        ),
    ]
